project:
  type: website

website:
  title: "Quarto social embeds"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Examples
        menu: 
        - examples/gists.qmd
        - examples/twitter.qmd
        - examples/vimeo.qmd
        - examples/youtube.qmd
    right:
      - icon: twitter
        href: https://twitter.com/sellorm
        aria-label: sellorm Twitter
      - icon: github
        href: https://github.com/sellorm/quarto-social-embeds
        aria-label: GitHub

format:
  html:
    theme: minty
    css: styles.css
    toc: true



